version: '3.9'

services:
  dev:
    image: node:14-alpine3.12
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: recruitment_api_development
    working_dir: /home/recruitment
    volumes:
      - ./:/home/recruitment
    ports:
      - '${PORT}:${PORT}'
    command: yarn start:dev
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - recruitment_networks
  debug:
    image: node:14-alpine3.12
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: recruitment_api_development
    working_dir: /home/recruitment
    volumes:
      - ./:/home/recruitment
    ports:
      - '${PORT}:${PORT}'
    command: yarn start:debug
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - recruitment_networks
  prod:
    image: node:14-alpine3.12
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: recruitment_api_product
    working_dir: /home/recruitment
    volumes:
      - ./:/home/recruitment
    ports:
      - '${PORT}:${PORT}'
    command: yarn start:prod
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - recruitment_networks
  database:
    container_name: recruitment_database
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
      TZ: GMT+7
    expose:
      - '${DATABASE_PORT}'
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - recruitment_networks

networks:
  recruitment_networks:
