version: '3.9'

services:
  application:
    image: node:14-alpine3.12
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: application
    working_dir: /home/recruitment
    volumes:
      - ./src:/home/recruitment/src
      - ./public:/home/recruitment/public
      - ./logs:/home/recruitment/logs
    environment:
      TZ: '${TIMEZONE}'
    ports:
      - '${PORT}:${PORT}'
    command: sh -c "yarn build && yarn start"
    restart: unless-stopped
    depends_on:
      - database
      - adminer
    networks:
      - recruitment_networks
  database:
    container_name: database
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
      TZ: '${TIMEZONE}'
      PGTZ: '${TIMEZONE}'
    expose:
      - '${DATABASE_PORT}'
    volumes:
      - ./data/development:/var/lib/postgresql/data
    networks:
      - recruitment_networks
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 5050:8080
    depends_on:
      - database
    networks:
      - recruitment_networks

networks:
  recruitment_networks:
