version: '3.9'

services:
  dev:
    build:
      dockerfile: ./Dockerfile
    container_name: recruitment_api_development
    working_dir: /home/recruitment
    volumes:
      - ./recruitment:/home/recruitment
    ports:
      - '${PORT}:${PORT}'
    command: yarn start:debug
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - recruitment_networks
  prod:
    build:
      dockerfile: ./Dockerfile
    container_name: recruitment_api_product
    working_dir: /home/recruitment
    volumes:
      - ./recruitment:/home/recruitment
    ports:
      - '${PORT}:${PORT}'
    command: yarn start:prod
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - recruitment_networks
  database:
    container_name: recruitment_database
    restart: always
    image: mysql:5.7.36
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      TZ: GMT+7
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - ./database/:/var/lib/mysql
    networks:
      - recruitment_networks

networks:
  recruitment_networks:
